frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\database\CallRecords;
use common\models\database\Role;
use common\models\database\User;
use frontend\models\SignupForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model
 * (for the extension) and the list for call-records.
 */
class UserController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    // Specify the available actions for an extension
                    [
                        'actions' => ['call-records', 'update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return @Yii::$app->user->getIdentity()->role_id == Role::ID_EXTENSION;
                        }
                    ],
                    // Specify the available actions for an operatior
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'call-records'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return @Yii::$app->user->getIdentity()->role_id == Role::ID_OPERATOR;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Extensions.
     * @return mixed
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find()->where(
                    'status=:status AND role_id=:roleID',
                    [
                        ':status' => User::STATUS_ACTIVE,
                        ':roleID' => Role::ID_EXTENSION
                    ]
            ),
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Extension's all call records.
     * @param integer $id
     * @return mixed
     */
    public function actionCallRecords($id) {
        if (
            @Yii::$app->user->getIdentity()->role_id == Role::ID_EXTENSION
            && Yii::$app->user->id != $id
        ) {
            throw new \yii\web\UnauthorizedHttpException();
        }

        $user = $this->findModel($id);

        $dataProvider = new ActiveDataProvider([
            'query' => CallRecords::find()->where(
                    'caller=:username OR callee=:username',
                    [
                        ':username' => $user->username,
                    ]
            ),
        ]);

        return $this->render('call-records', [
                    'dataProvider' => $dataProvider,
                    'user' => $user
        ]);
    }

    /**
     * Creates a new Extension.
     * If creation is successful, the browser will be redirected to the 'extension list' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                Yii::$app->getSession()->setFlash('success', 'Extension successfully created');
                return $this->redirect(['user/index']);
            }
        }

        return $this->render('//site/signup', [
                    'model' => $model,
        ]);

    }

    /**
     * Updates an existing Extension.
     * If update is successful, the browser will be redirected to the 'extension list' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        // Deny access from the current logined extension
        // if the update request not belongs to him/her
        if (
            @Yii::$app->user->getIdentity()->role_id == Role::ID_EXTENSION
            && Yii::$app->user->id != $id
        ) {
            throw new \yii\web\UnauthorizedHttpException();
        }
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Successfull update.');
            // Don't redirect in case of current user is an extension
            switch (Yii::$app->user->getIdentity()->role_id) {
                case Role::ID_EXTENSION:
                    break;
                default: 
                    return $this->redirect(['index']);
                    break;
            }
            
        }
        
        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Extension.
     * (Changes the status of the user to deleted)
     * If deletion is successful, the browser will be redirected to the 'extension list' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);
        $model->status = User::STATUS_DELETED;
        if ($model->save()) {
            Yii::$app->getSession()->setFlash('success', 'Successfull delete.');
        } else {
            Yii::$app->session->setFlash('error', 'There was an error deleting extension.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Extension (User) based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        $model = User::find()->where(
                        'id=:ID AND status=:status AND role_id=:roleID', [
                            ':ID' => $id,
                            ':status' => User::STATUS_ACTIVE,
                            ':roleID' => Role::ID_EXTENSION
                        ]
                )->one();

        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'Webdeveloper Test',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                switch (Yii::$app->user->getIdentity()->role_id) {
                    // If current user is operator
                    case common\models\database\Role::ID_OPERATOR:
                        $menuItems = [
                            ['label' => 'Extensions', 'url' => ['/user/index']],
                        ];
                        break;
                    // If current user is extension
                    case common\models\database\Role::ID_EXTENSION:
                        $menuItems = [
                            ['label' => 'Update', 'url' => ['/user/update', 'id' => Yii::$app->user->getId()]],
                            ['label' => 'Call Records', 'url' => ['/user/call-records', 'id' => Yii::$app->user->getId()]],
                        ];
                        break;
                }
                

                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; Peter Varga <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>